{
 "title": "ETA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of disk read and write operations",
   "type": "graph",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readcount[10m])"
    },
    {
     "expr": "rate(system_disk_writecount[10m])"
    }
   ]
  },
  {
   "title": "Last synced block",
   "type": "graph",
   "gridPos": { "h": 26, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "chain_head_block" }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "stat",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_peers" }
   ]
  }
 ]
}